### PR TITLE
Bump QEMU to 8.1.0

### PR DESCRIPTION
**Pull request by scribam**

### CODE REVIEW

**Comment by jacob-carlborg** [comment]
Have you tested this change?

**Comment by scribam** [comment]
No, I haven't.
How do you usually test? Do I have to create a release in https://github.com/scribam/resources and then fork https://github.com/cross-platform-actions/action and change `resourceUrl`/`resourcesUrl` everywhere?

**Comment by jacob-carlborg** [comment]
> How do you usually test? Do I have to create a release in https://github.com/scribam/resources and then fork https://github.com/cross-platform-actions/action and change resourceUrl/resourcesUrl everywhere?

Yes, that's basically it. I think you only need to change the URL in one place. If you push a tag it will automatically build and create a draft release, you only need to publish it. 

You can also run the action locally, using a tool called `act`. But then you need to compile QEMU as well, which takes a while. There's some instructions for that in the readme of the action: https://github.com/cross-platform-actions/action#running-end-to-end-tests.

**Comment by jacob-carlborg** [comment]
Seems like something breaks for OpenBSD: https://github.com/cross-platform-actions/action/actions/runs/6096325544.

**Pull request closed without merging**
