### PR TITLE
Bump QEMU to 8.0.3

### PR DESCRIPTION
**Pull request by scribam**

### CODE REVIEW

**Comment by jacob-carlborg** [comment]
Have you tested this change with the actual action?

**Comment by scribam** [comment]
No, I haven't

**Review by jacob-carlborg — APPROVED** [review]

**Comment by jacob-carlborg** [comment]
Thanks.

**Comment by jacob-carlborg** [comment]
Available now in https://github.com/cross-platform-actions/action/releases/tag/v0.17.0.

**Pull request merged**
